apiVersion: v1
kind: Secret
metadata:
  name: my-object-storage-secret
type: Opaque
data:
  accessKeyId: YWplbGM3cWM5NDgwcjk4ZHVzdm8=
  secretAccessKey: WUNNUDI3YVRVaHZyaWIwZjlfOU1jQkl3V1VXaTNfSGJMRDhzT25VSA==
