---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen       8000;
          server_name  localhost;
          location / {
            root   /homework;
            index  index.html;
        }
      }
    }