apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000