apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
        - name: nginx
          image: my-nginx:0.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/conf.d

        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:latest
          args: ["-nginx.scrape-uri", "http://localhost:80/metrics"]
          ports:
            - containerPort: 9113

      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx_status.conf: |
    server {
        listen 80;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /metrics {
            stub_status on;
            allow 127.0.0.1;
            deny all;
        }
    }
