apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus-cred
  namespace: vault
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-secret-store
  target:
    name: otus-cred
  data:
    - secretKey: username
      remoteRef:
        key: otus/cred
        property: username
    - secretKey: password
      remoteRef:
        key: otus/cred
        property: password
