---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Values.deployment.namespace}}
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen       8000;
          server_name  localhost;
          location / {
            root /homework;
            index index.html;
        }
          location /conf/file {
            alias /homework/conf;
            autoindex on;
            autoindex_format html;
        }
          location /metrics.html {
            alias /homework/metrics.html;
          }
      }
    }
    