apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | required "deployment configuration is required" }} 
  namespace: {{ .Values.deployment.namespace}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.selector_app }}
  ports:
  - name: {{ .Values.service.ports.name }}
    protocol: {{ .Values.service.ports.protocol }}
    port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.deployment.containers.ports }}