apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: homework
  labels:
    app: init
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Privet medved' > /init/index.html"]
    volumeMounts:
    - name: shared-volume
      mountPath: /init
  containers:
  - name: web-server
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-volume
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
  volumes:
  - name: shared-volume
    emptyDir: {}
  terminationGracePeriodSeconds: 1
  dnsPolicy: Default